trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20'
  artifactName: 'react-build'
  storageAccountName: 'tfstate123000s178'


stages:

- stage: Build
  displayName: Build React Application

  jobs:
  - job: BuildReact

    steps:

    - checkout: self

    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
        versionSpec: $(nodeVersion)

    - script: |
        npm install
        npm run build
        ls -la dist
      displayName: Build React Application


    - task: PublishPipelineArtifact@1
      displayName: Publish React Artifact
      inputs:
        targetPath: 'dist'
        artifact: $(artifactName)



- stage: Deploy
  displayName: Deploy React to Azure Storage

  dependsOn: Build

  jobs:

  - job: DeployStorage

    displayName: Upload React Files

    steps:

    - download: current
      artifact: $(artifactName)


    - task: AzureCLI@2
      displayName: Deploy to Azure Storage Static Website

      inputs:
        azureSubscription: 'arm -connection'
        scriptType: bash
        scriptLocation: inlineScript

        inlineScript: |

          az storage blob upload-batch \
          --account-name $(storageAccountName) \
          --destination '$web' \
          --source "$(Pipeline.Workspace)/$(artifactName)" \
          --overwrite