trigger:
- main

variables:
  nodeVersion: '20.x'
  imageName: frontend
  acrName: portfolio1.azurecr.io
  imageTag: $(Build.BuildId)


# ======================
# BUILD AND PUSH IMAGE
# ======================

stages:

- stage: Build
  displayName: Build and Push Docker Image

  jobs:

  - job: DockerBuild

    pool:
      vmImage: ubuntu-latest

    steps:

    - checkout: self


    # Optional React validation build
    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
        versionSpec: $(nodeVersion)


    - script: |
        npm install
        npm run build
        ls -la dist
      displayName: Validate React Build


    - task: Docker@2
      displayName: Build and Push Image

      inputs:

        containerRegistry: acr-connection

        repository: $(imageName)

        command: buildAndPush

        Dockerfile: Dockerfile

        tags: |
          $(imageTag)



# ======================
# DEPLOY EAST CLUSTER
# ======================


- stage: Deploy_East

  displayName: Deploy To East AKS

  dependsOn: Build


  jobs:

  - deployment: DeployEast

    displayName: AKS East Deployment

    environment: aks-east


    pool:

      vmImage: ubuntu-latest


    strategy:

      runOnce:

        deploy:

          steps:
            - checkout: self


            - task: KubernetesManifest@1

              displayName: Deploy Frontend East

              inputs:
               action: 'deploy'
               connectionType: 'kubernetesServiceConnection'
               kubernetesServiceConnection: 'aks-east-connection'
               namespace: 'default'
               manifests: '$(Build.SourcesDirectory)/k8s/frontend-deployment.yaml'
               containers: '$(acrName)/$(imageName):$(imageTag)'




